# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bpm', models.IntegerField(default=0)),
                ('current_time', models.DateTimeField(verbose_name=' TIME ')),
            ],
        ),
    ]
